# This is a Visual Studio extension installation task for Dev Box. 
# It accepts a Markplace Item Name (as used in the URI of a given Visual Studio Extension Maketplace entry)
#
# USAGE
#
# - task: install-vs-extension
#     inputs:
#       marketplaceItemName: "GitHub.copilotvs"
#


name: install-vs-extension
description: Installs a Visual Studio extension
author: Microsoft Corporation
command: ".\\Install-VSIXExtension.ps1 -MarketplaceItemName {{marketplaceItemName}}"
inputs:
  marketplaceItemName:
    type: string
    required: true
    description: |
      The name of the Visual Studio extension to install.
      For example, "GitHub.copilotvs".
      Visit https://marketplace.visualstudio.com to learn
      more about Visual Studio extensions.
