# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: VmwithStorage-template
version: 1.0.0
summary: Azure VM and Storage Environment
description: Deploys an Azure VM with Storage, it is compatible with azd.
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: vmName
    type: string
    description: Name of the Virtual Machine
  
  - id: storageAccountName
    type: string
    description: Name of the Storage Account

  - id: vnetName
    type: string
    description: Name of the Virtual Network
  
  - id: subnetName
    type: string
    description: Name of the Subnet
  
  - id: nicName
    type: string
    description: Name of the Network Interface Card

  - id: addressPrefix
    type: string
    description: Address prefix for the Virtual Network
  - id: subnetPrefix
    type: string
    description: Address prefix for the Subnet

  - id: adminUsername
    type: string
    description: Admin username for the Virtual Machine

  - id: adminPassword
    type: securestring
    description: Admin password for the Virtual Machine

  - id: location
    type: string
    description: Azure region for deployment
    allowed:
      - eastus
      - westus
      - westeurope
      - southeastasia

  - id: vmSize
    type: string
    description: Size of the Virtual Machine
    default: Standard_DS1_v2

  - id: osType
    type: string
    description: Operating system type
    allowed:
      - Windows
      - Linux

  - id: diskSizeGB
    type: int
    description: Size of the OS disk in GB
    default: 128

  - id: publicIpAddressType
    type: string
    description: Public IP address allocation method
    allowed:
      - Dynamic
      - Static

  - id: resourceGroup
    type: string
    description: Name of the resource group to deploy resources into