parameters:
  - id: vmName
    type: string
    description: Name of the Virtual Machine

  - id: adminUsername
    type: string
    description: Admin username for the Virtual Machine

  - id: adminPassword
    type: securestring
    description: Admin password for the Virtual Machine

  - id: location
    type: string
    description: Azure region for deployment
    allowed:
      - eastus
      - westus
      - westeurope
      - southeastasia

  - id: storageAccountType
    type: string
    description: Type of storage account
    allowed:
      - Standard_LRS
      - Standard_GRS
      - Standard_ZRS
      - Premium_LRS

  - id: vmSize
    type: string
    description: Size of the Virtual Machine
    default: Standard_DS1_v2

  - id: osType
    type: string
    description: Operating system type
    allowed:
      - Windows
      - Linux

  - id: diskSizeGB
    type: int
    description: Size of the OS disk in GB
    default: 128

  - id: vnetName
    type: string
    description: Name of the Virtual Network

  - id: subnetName
    type: string
    description: Name of the Subnet

  - id: publicIpAddressType
    type: string
    description: Public IP address allocation method
    allowed:
      - Dynamic
      - Static