name: VMwithStorage-template
summary: Deployment of a Virtual Machine with a Storage Account.
description: Deploys a Virtual Machine with a System-Assigned Managed Identity, a Storage Account. 
runner: ARM
templatePath: azuredeploy.json
