name: vm-with-storage
resourceType: Microsoft.Resources/deployments
location: [resourceGroup().location]
parameters:
  adminUsername:
    type: string
    description: Admin username for the VM
  adminPassword:
    type: securestring
    description: Admin password for the VM
  vmName:
    type: string
    description: Name of the virtual machine
  vmSize:
    type: string
    default: Standard_DS1_v2
    description: Size of the virtual machine
  storageAccountType:
    type: string
    default: Standard_LRS
    description: Type of storage account
  osDiskSizeGB:
    type: int
    default: 128
    description: Size of the OS disk in GB
template:
  file: azuredeploy.json
  parameters:
    adminUsername: $(adminUsername)
    adminPassword: $(adminPassword)
    vmName: $(vmName)
    vmSize: $(vmSize)
    storageAccountType: $(storageAccountType)
    osDiskSizeGB: $(osDiskSizeGB)
outputs:
  vmId:
    type: string
    description: Resource ID of the deployed VM
  publicIpAddress:
    type: string
    description: Public IP address of the VM