name: VMStorageConfig
summary: Deployment of a Virtual Machine with a Storage Account using Bicep.
description: Deploys a Virtual Machine with a System-Assigned Managed Identity, a Storage Account, a Virtual Network, and a Network Interface. Assigns the VM the "Storage Blob Data Contributor" role for the Storage Account.
templatePath: main.bicep
parameters:
- id: "vmName"
  name: "Virtual Machine Name"
  description: "Name of the Virtual Machine to be deployed."
  type: "string"
  default: "myVM"
- id: "location"
  name: "Location"
  description: "Azure region where the resources will be deployed."
  type: "string"
  default: "[resourceGroup().location]"
- id: "adminUsername"
  name: "Admin Username"
  description: "Admin username for the Virtual Machine."
  type: "string"
  default: "azureuser"
- id: "adminPassword"
  name: "Admin Password"
  description: "Admin password for the Virtual Machine."
  type: "securestring"
- id: "storageAccountName"
  name: "Storage Account Name"
  description: "Name of the Storage Account to be created."
  type: "string"
  default: "mystorageacct"
- id: "storageSku"
  name: "Storage SKU"
  description: "SKU for the Storage Account."
  type: "string"
  default: "Standard_LRS"
  allowed:
    - "Standard_LRS"
    - "Standard_GRS"
    - "Standard_ZRS"
    - "Premium_LRS"
- id: "vmSize"
  name: "Virtual Machine Size"
  description: "Size of the Virtual Machine."
  type: "string"
  default: "Standard_DS1_v2"
  allowed:
    - "Standard_DS1_v2"
    - "Standard_DS2_v2"
    - "Standard_B1s"
    - "Standard_B2s"
- id: "imageReference"
  name: "OS Image Reference"
  description: "Reference to the OS image for the Virtual Machine."
  type: "object"
  default:
    publisher: "Canonical"
    offer: "UbuntuServer"
    sku: "18.04-LTS"
    version: "latest"
runner: Bicep